name = "Squawkypack"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e654a3f6fb9e506601b932dc57092c216e1ab0d8fb48efb8b5e9957880493ff"

[versions] 
forge = "47.2.17"
minecraft = "1.20.1"
