name = "Squawkypack"
author = "Squawkykaka"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "248ed01021801045a35a63411b91e55befab55d8fb25373526c096787ccc1de7"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
