name = "Squawkypack"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f06dec3e8408f2f72da53ecfd3ed24a848aa135e804252cc829d2f9cde990a8e"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
