name = "Squawkypack"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7edb49493b6ae32b1c2b34c685e212bc4270df9672f1abb8533aaf4d380c6e18"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
