name = "Squawkypack"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5d31d4e453609653e6c303796117d1413cc5bc2188904b0c33065914de16ce3"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
