name = "Squawkypack"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a20d0f27488cea828219bb9c0a6171cbbd6097b67d8b504654a6080c406723bd"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
