name = "Squawkypack"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fce91b046b96af714060dd758c262fdb1630572b4db22ad15b9c7cf019be0d6"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
