name = "Squawkypack"
author = "Squawkykaka"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "847a0f422537b9bca9fd3b474860df036d9f0ca35475ef85713760f1189ccf3d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
