name = "Squawkypack"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43ac04b81bbb9571304bf2afae18688851d2921895c3eb9075e6d4a9e8cdf1b2"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
